name: img_proc
channels:
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - matplotlib=3.3.4
  - pytest=6.2.1
  - python-dotenv=0.15.0
  - simpleitk=2.0.2
  # - conda-forge::opencv=4.1.0
  - opencv=4.5.1
